-intstyle "ise" -incremental -lib "secureip" -o "/home/ise/CSE_450_Xilinx/Faiza_VLSI/adder_8bit_tb_isim_beh.exe" -prj "/home/ise/CSE_450_Xilinx/Faiza_VLSI/adder_8bit_tb_beh.prj" "work.adder_8bit_tb" 
